<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Abdibogoreh</title>
  <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>

	<div id="follow">
		<p>This element will follow you all the way down the page</p>
		<p>You can hide it by clicking on it.</p>
	</div>

			Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l'imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n'a pas fait que survivre cinq siècles, mais s'est aussi adapté à la bureautique informatique, sans que son contenu n'en soit modifié. Il a été popularisé dans les années 1960 grâce à la vente de feuilles Letraset contenant des passages du Lorem Ipsum, et, plus récemment, par son inclusion dans des applications de mise en page de texte, comme Aldus PageMaker.
			Bing is a web search engine owned and operated by Microsoft. The service has its origins in Microsoft's previous search engines: MSN Search, Windows Live Search and later Live Search. Bing provides a variety of search services, including web, video, image and map search products. It is developed using ASP.NET.
			Bing, Microsoft's replacement for Live Search, was unveiled by Microsoft CEO Steve Ballmer on May 28, 2009, at the All Things Digital conference in San Diego, California, for release on June 1, 2009.[3] Notable new features at the time included the listing of search suggestions while queries are entered and a list of related searches (called "Explore pane") based on semantic technology from Powerset,[4] which Microsoft had acquired in 2008.[5]
			In July 2009, Microsoft and Yahoo! announced a deal in which Bing would power Yahoo! Search.[6] All Yahoo! Search global customers and partners made the transition by early 2012.[7] The deal was altered in 2015, meaning Yahoo! was only required to use Bing for a "majority" of searches.[8]
			In October 2011, Microsoft stated that they were working on new back-end search infrastructure with the goal of delivering faster and slightly more relevant search results for users. Known as "Tiger", the new index-serving technology had been incorporated into Bing globally since August that year.[9] In May 2012, Microsoft announced another redesign of its search engine that includes "Sidebar", a social feature that searches users' social networks for information relevant to the search query.[10]
			As of November 2015, Bing is the second largest desktop search engine in the US, with a query volume of 20.9%, behind Google on 63.9%. Yahoo! Search, which Bing largely powers, has 12.5%.[11]
			 public beta of Windows Live Search was unveiled on March 8, 2006, with the final release on September 11, 2006 replacing MSN Search. The new search engine used search tabs that include Web, news, images, music, desktop, local, and Microsoft Encarta.
			In the roll-over from MSN Search to Windows Live Search, Microsoft stopped using Picsearch as their image search provider and started performing their own image search, fueled by their own internal image search algorithms.[12].
			Microsoft originally launched MSN Search in the third quarter of 1998, using search results from Inktomi. It consisted of a search engine, index, and web crawler. In early 1999, MSN Search launched a version which displayed listings from Looksmart blended with results from Inktomi except for a short time in 1999 when results from AltaVista were used instead. Since then Microsoft upgraded MSN Search to provide its own self-built search engine results, the index of which was updated weekly and sometimes daily. The upgrade started as a beta program in November 2004, and came out of beta in February 2005. Image search was powered by a third party, Picsearch. The service also started providing its search results to other search engine portals in an effort to better compete in the market.
			On March 21, 2007, Microsoft announced that it would separate its search developments from the Windows Live services family, rebranding the service as Live Search. Live Search was integrated into the Live Search and Ad Platform headed by Satya Nadella, part of Microsoft's Platform and Systems division. As part of this change, Live Search was merged with Microsoft adCenter.[13]
			A series of reorganisations and consolidations of Microsoft's search offerings were made under the Live Search branding. On May 23, 2008, Microsoft announced the discontinuation of Live Search Books and Live Search Academic and integrated all academic and book search results into regular search, and as a result this also included the closure of Live Search Books Publisher Program. Soon after, Windows Live Expo was discontinued on July 31, 2008. Live Search Macros, a service for users to create their own custom search engines or use macros created by other users, was also discontinued shortly after. On May 15, 2009, Live Product Upload, a service which allowed merchants to upload products information onto Live Search Products, was discontinued. The final reorganisation came as Live Search QnA was rebranded as MSN QnA on February 18, 2009, however, it was subsequently discontinued on May 21, 2009.[14].
			On sait depuis longtemps que travailler avec du texte lisible et contenant du sens est source de distractions, et empêche de se concentrer sur la mise en page elle-même. L'avantage du Lorem Ipsum sur un texte générique comme 'Du texte. Du texte. Du texte.' est qu'il possède une distribution de lettres plus ou moins normale, et en tout cas comparable avec celle du français standard. De nombreuses suites logicielles de mise en page ou éditeurs de sites Web ont fait du Lorem Ipsum leur faux texte par défaut, et une recherche pour 'Lorem Ipsum' vous conduira vers de nombreux sites qui n'en sont encore qu'à leur phase de construction. Plusieurs versions sont apparues avec le temps, parfois par accident, souvent intentionnellement (histoire d'y rajouter de petits clins d'oeil, voire des phrases embarassantes).
			Contrairement à une opinion répandue, le Lorem Ipsum n'est pas simplement du texte aléatoire. Il trouve ses racines dans une oeuvre de la littérature latine classique datant de 45 av. J.-C., le rendant vieux de 2000 ans. Un professeur du Hampden-Sydney College, en Virginie, s'est intéressé à un des mots latins les plus obscurs, consectetur, extrait d'un passage du Lorem Ipsum, et en étudiant tous les usages de ce mot dans la littérature classique, découvrit la source incontestable du Lorem Ipsum. Il provient en fait des sections 1.10.32 et 1.10.33 du "De Finibus Bonorum et Malorum" (Des Suprêmes Biens et des Suprêmes Maux) de Cicéron. Cet ouvrage, très populaire pendant la Renaissance, est un traité sur la théorie de l'éthique. Les premières lignes du Lorem Ipsum, "Lorem ipsum dolor sit amet...", proviennent de la section 1.10.32.
			L'extrait standard de Lorem Ipsum utilisé depuis le XVIè siècle est reproduit ci-dessous pour les curieux. Les sections 1.10.32 et 1.10.33 du "De Finibus Bonorum et Malorum" de Cicéron sont aussi reproduites dans leur version originale, accompagnée de la traduction anglaise de H. Rackham (1914).
			Plusieurs variations de Lorem Ipsum peuvent être trouvées ici ou là, mais la majeure partie d'entre elles a été altérée par l'addition d'humour ou de mots aléatoires qui ne ressemblent pas une seconde à du texte standard. Si vous voulez utiliser un passage du Lorem Ipsum, vous devez être sûr qu'il n'y a rien d'embarrassant caché dans le texte. Tous les générateurs de Lorem Ipsum sur Internet tendent à reproduire le même extrait sans fin, ce qui fait de lipsum.com le seul vrai générateur de Lorem Ipsum. Iil utilise un dictionnaire de plus de 200 mots latins, en combinaison de plusieurs structures de phrases, pour générer un Lorem Ipsum irréprochable. Le Lorem Ipsum ainsi obtenu ne contient aucune répétition, ni ne contient des mots farfelus, ou des touches d'humour.
			On sait depuis longtemps que travailler avec du texte lisible et contenant du sens est source de distractions, et empêche de se concentrer sur la mise en page elle-même. L'avantage du Lorem Ipsum sur un texte générique comme 'Du texte. Du texte. Du texte.' est qu'il possède une distribution de lettres plus ou moins normale, et en tout cas comparable avec celle du français standard. De nombreuses suites logicielles de mise en page ou éditeurs de sites Web ont fait du Lorem Ipsum leur faux texte par défaut, et une recherche pour 'Lorem Ipsum' vous conduira vers de nombreux sites qui n'en sont encore qu'à leur phase de construction. Plusieurs versions sont apparues avec le temps, parfois par accident, souvent intentionnellement (histoire d'y rajouter de petits clins d'oeil, voire des phrases embarassantes).
			Microsoft recognised that there would be a problem with branding as long as the word "Live" remained in the name.[15] As an effort to create a new identity for Microsoft's search services, Live Search was officially replaced by Bing on June 3, 2009.[16]
			The Bing name was chosen through focus groups, and Microsoft decided that the name was memorable, short, easy to spell, and that it would function well as a URL around the world. The word would remind people of the sound made during "the moment of discovery and decision making."[17] Microsoft was assisted by branding consultancy Interbrand in their search for the best name for the new search engine.[18] The name also has strong similarity to the word 'bingo', which is used to mean that something sought has been found or realized, as is interjected when winning the game Bingo. Microsoft advertising strategist David Webster originally proposed the name "Bang" for the same reasons the name Bing was ultimately chosen (easy to spell, one syllable, and easy to remember). He noted, "It's there, it's an exclamation point [...] It's the opposite of a question mark." This name was ultimately not chosen because it could not be properly used as a verb in the context of an internet search; Webster commented "Oh, 'I banged it' is very different than 'I binged it'".[19]
			According to the Guardian "[Microsoft] hasn't confirmed that it stands recursively for Bing Is Not Google, but that's the sort of joke software engineers enjoy."[20] Qi Lu, president of Microsoft Online Services, also announced that Bing's official Chinese name is bì yìng (simplified Chinese: 必应; traditional Chinese: 必應), which literally means "very certain to respond" or "very certain to answer" in Chinese.[21]
			While being tested internally by Microsoft employees, Bing's codename was Kumo (くも),[22] which came from the Japanese word for spider (蜘蛛; くも, kumo) as well as cloud (雲; くも, kumo), referring to the manner in which search engines "spider" Internet resources to add them to their database, as well as cloud computing.
			On July 31, 2009, The Laptop Company, Inc. stated in a press release that it would challenge Bing's trademark application, alleging that Bing may cause confusion in the marketplace as Bing and their product BongoBing both do online product search.[23] Software company TeraByte Unlimited, which has a product called BootIt Next Generation (abbreviated to BING), also contended the trademark application on similar grounds, as did a Missouri-based design company called Bing! Information Design.[24]
			Microsoft contended that claims challenging its trademark were without merit because these companies filed for U.S. federal trademark applications only after Microsoft filed for the Bing trademark in March 2009.[25]

  <script type="text/javascript" src="jquery.js"></script>
  <script type="text/javascript" src="div.js"></script>
</body>
</html>
